name: CI

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  auto_merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge pull request
        if: success() && github.event.pull_request.merged == false
        run: |
          git config --global user.name 'interstellar-bot'
          git config --global user.email 'interstellar-bot@outlook.com'
          if [ "${{ github.ref }}" == "refs/head/main" ]; then
            git merge --no-ff --no-edit ${{ github.event.pull_request.head.sha }}
          fi
